### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by irondavy** [ckolderup/picaro#1]
We should decide on some official terminology to be used on any public-facing documentation. Off the top of my head, some terms we'll need to settle on:
- The name of the thing people are interacting with. "Game" seems like the most obvious, but I also find "Story" very appealing. Not quite as loaded as "Game", in my opinion.
- The name of the person interacting with the game. Even though I favor "Story" over "Game", I think I prefer "Player" over something like "Reader". Is there anything else?
- The name of the person who creates the games. "Author"? "Writer"? "Creator"? Not sure...
- The name of the game file, the JSON. If we go with "Game" then "File" might actually be right. "Script" and "Code" are also interesting.

**Comment by ardubs** [comment]
I have some opinions on this:
- I think I favor "story" for #1, mostly because of the loadedness
  issue David mentioned.
- I like "player" ok for number two, but I wonder if a left-field term
  (a la "picaro") could work more in our favor. Maybe something like
  "visitor."
- I strongly favor "writer" for this, because my experience has been
  that 90% of the work that goes into one of these, prose or code, is
  writing.
- I think I like script for this, but something like "map" could be
  cool, especially if we go with "visitor."

On Mon, Jan 23, 2012 at 12:47 AM, David Cole
reply@reply.github.com
wrote:

**Comment by ckolderup** [comment]
I think "visitor" can be confusing— on the web, "visitor" is often a euphemism for "this person has no relationship with this site". Would you want to be called a "visitor" when you've been writing works of art and sharing them every day for two years?

I'm fine with "story" and "writer" (although I think "author" is more distinguished and has all of the same meaning... is it too "we're trying to sound fancy"?)

**Comment by ardubs** [comment]
good point! visitor withdrawn.

**Comment by ckolderup** [comment]
I _do_ like the thought of having some kind of unique terminology there. "User" is boring and so generic with sites of all kinds that it doesn't properly communicate the level of engagement we're looking for here. "Player," though, goes pretty tightly with "game", so if we're avoiding the latter then maybe we should the former as well. Still thinking about this...

**Comment by irondavy** [comment]
I like "writer" because you write code and you write fiction, but you don't often hear people saying you "author" code. The fact that "writer" is generic enough for both is nice, and appropriate.

**Comment by ckolderup** [comment]
Makes sense. So:
- Game -> Story
- Creator -> Writer
- JSON -> ???
- Player -> ???

What about "script" and "actor" for the last two? Does that make you feel involved in the story? I liked the idea of "map" and (something) to go along with the prominent compass rose concept. Some kind of "traveler"? Some other term from the [Picaresque](http://en.wikipedia.org/wiki/Picaresque) concept?

**Comment by ardubs** [comment]
david and i were throwing around "blueprint" for the JSON last night, which i kinda like but doesn't really work with "writer."

**Comment by irondavy** [comment]
I'm keen on "script", as "script" is also one of those terms that's broad enough to be both about traditional writing and coding. I'm less excited about "actor" personally. Maybe "player" works just because player connotes both game and theater, as "script" does.

**Comment by irondavy** [comment]
Okay, I'm going to call these as final, unless anyone objects:
- Story
- Player
- Writer
- Script

A few more terms to settle on:
- The generic term for things added to scripts, comprising items, NPCs, rooms, paths, etc. Maybe we don't actually need a term for this? In my head I think of them as the "nouns" of the script.
- The generic term for things the player does: Actions or Verbs. The pairing of Nouns and Verbs sounds nice to me.
- The name of physical objects in games. Item or object seem the most natural, item being the most game-y.
- The name of non-player characters. NPC is very game-y but maybe just Character is better?
- Rooms and paths, any reason not to use Room and Path? I don't think so, but I just want to make sure we're not accepting old false assumptions.

**Comment by irondavy** [comment]
For now I'm going to call them Nouns, Verbs, Items, Rooms, and Paths.

Character support has been backlogged. Closing until we need to reexamine this.
