### ISSUE TITLE
The CoffeeScript Question

### ISSUE THREAD

**Issue by hoverbird** [ckolderup/picaro#12]
I know there are a lot of Coffee drinkers working on Picaro.  As the JS app grows, I find myself wanting some of the brevity and expressiveness of CS features.  Since I missed a lot of the early development conversations, I don't know if this has been seriously discussed yet.  If not- how do people feel about migrating to Coffee gradually?  What are the pros and cons that are important to y'all?

**Comment by ckolderup** [comment]
I barely know either, so I'm fine with going with whichever works best for you guys; especially since I'm not currently touching the Javascript side of things anyway. (I'll be happy to contribute where I can once there isn't a large list of equally important things to do server-side.) I do think Coffeescript looks nice, so I'd be happy to get some experience with it.

**Comment by dongle** [comment]
To consider: coffeescript is syntactically simpler and enforces certain coding patterns, so it might make sense to settle on coffeescript if you want to expose some of it to users.

**Comment by hoverbird** [comment]
@dongle totally agreed that CS is more beginner-friendly.  @ckolderup glad to hear it.  we can add Guard as a dependency and have it automatically compile modified .coffeescript files on each request, during development.

**Comment by jamiew** [comment]
fwiw I think http://peanutty.org does a good job of showing that newbs and coffeescript can get along. 

I'm still relatively new to CS but as long as there's no extra compilation steps I always think it's chill a+ zone

**Comment by hoverbird** [comment]
@jamiew Agreed. The only place where CS can sometimes fall down for folks is debugging, and as long as you have two prerequisites it's really a non-issue. The 2 things that help are: an immediate growl alert if you ever write uncompileable code (which Guard provides) and a good understanding of your browser's debugging tools.

Some folks complain about having to sift through generated code to find bugs, but I never see that- just dropping a breakpoint into your CS source will bring you right to the relevant spot in the JS.

**Comment by hoverbird** [comment]
So it sounds like there are no objections / devil's advocates?  Just so long as everyone feels like they understand the tradeoffs, I'm down to push this to master.

**Comment by JoeBernardi** [comment]
Push away. I could have sworn I had commented in here yesterday about how the CS-ification was lookin' good so far. (though I'm far from being as familiar with it as I could be). Seems like the kind of thing that will help clean up the code in the long run given the data model we seem to be going with.

**Comment by hoverbird** [comment]
Awesome, going ahead with this.  The last thing that we'll probably need to figure out is the concat + compilation + minification pipeline for deploying to heroku.  Who's managing the deploy process right now, @ckolderup?

**Comment by ckolderup** [comment]
We hadn't discussed it, but I can take that on no problem. I'll whip up a rake task soon and open a pull request for feedback in case you guys have any suggestions.
