### ISSUE TITLE
We need visual feedback when a game is won or lost

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/picaro#14]
It should end the game with a win message or something.

**Comment by hoverbird** [comment]
I can easily tack on a message like "the game is won" but I was wondering if there is a more definitive way to message this.   Any ideas, @irondavy?

**Comment by irondavy** [comment]
Here's what I'm thinking:

![](http://f.cl.ly/items/2L0Z231F0C0C0y1F3a2C/Screen%20Shot%202012-03-04%20at%209.05.17%20PM.png)

I pushed the CSS for this: `#game p.end`.

It would also be worth considering sliding the verb bar off the screen at this point as well.

**Comment by irondavy** [comment]
I don't expect the links to do anything in V1, certainly.

**Comment by ckolderup** [comment]
The links are pretty easy. "/games/by/{username}" and then just look up the proper syntax for twitter/facebook share URLs to "/game/{slug}". I'm sure we can get those in there in some fashion.

**Comment by irondavy** [comment]
Clearing myself as assignee since the design is done, and CSS is checked in.

**Comment by ardubs** [comment]
this looks lovely. nice!

**Comment by hoverbird** [comment]
Awesome!

**Comment by hoverbird** [comment]
This works now. It should show the message attached to the win event, and it displays the author's name as a link as shown above.
