### ISSUE TITLE
Allow players to Use items on themselves

### ISSUE THREAD

**Issue by hoverbird** [ckolderup/picaro#20]
I'm thinking there will be a special "Self" list item in the Use menu, at least for the time being.

**Comment by irondavy** [comment]
Yep, absolutely.

On Tue, Feb 21, 2012 at 10:24 AM, Patrick Ewing <
reply@reply.github.com

**Comment by hoverbird** [comment]
Done!  You can name your "self" whatever you want, or omit it entirely.  It must merely have an id of self in the "specialObjects" section of the JSON.
