### ISSUE TITLE
Blinking room names on compass rose hover

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/picaro#24]
Sometimes when I hover over a direction on the compass rose, the room name above it blinks 2-4 times before staying in place.

I'm using Chrome 17 on Mac OS X 10.7.2.

**Comment by JoeBernardi** [comment]
For some reason the mouseover event was being triggered multiple times (2, then 3, then 4, etc) on, uh, mouseover. I changed it from separate mouseover() and mouseout() functions to one hover() function with mouseover and mouseout parameters and it seems to work now. This raises bigger concerns about event handling in ui.js, but I guess we'll cross that bridge when we get to it??
