### ISSUE TITLE
Tapping/clicking on the verb again should close the popover

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/picaro#25]
On the iPhone, I find myself wanting to tap on the toolbar icon for the currently open verb as a way to close/cancel out of it. I know there's already a back arrow and the ability to click on the main status area, but would it make sense to anyone else for this to work as well?

**Comment by hoverbird** [comment]
I say YAIS.

**Comment by irondavy** [comment]
Yes, this was the intended behavior. The back arrow is meant when you're in
step 2 of a verb that takes two nouns, not a way to close the window. You
should also be able to dismiss the verb modal by tapping anywhere outside
of it.

On Sun, Feb 26, 2012 at 8:18 PM, Casey Kolderup <
reply@reply.github.com

**Comment by ardubs** [comment]
I've caught myself trying to close them that way as well, FWIW

On Sun, Feb 26, 2012 at 11:18 PM, Casey Kolderup
reply@reply.github.com
wrote:

**Comment by JoeBernardi** [comment]
$$$ Done $$$. Boy oh boy could ui.js use some cleaning up.
