### ISSUE TITLE
The Title Bar doesn't work well with longer room names

### ISSUE THREAD

**Issue by hoverbird** [ckolderup/picaro#28]
See: http://picaro.heroku.com/play/hohum

Could solve this with som CSS overflow magic, JS truncation,  a hard limit on the length of room names...

**Comment by irondavy** [comment]
Anyone object to hard limiting the length of room names? This is going to be a problem in the build UI as well and I don't think the downsides will be huge if we character limit room names. Less is more is the Picaro way.

**Comment by ardubs** [comment]
no objection, and come to think of it, i'd be down for putting a similar limit on the length of room descriptions/text fields in general

**Comment by hoverbird** [comment]
No objections here!  Let me know a good limit and I can add it to the game validator.

**Comment by irondavy** [comment]
I'm getting 16-24 in tests so let's call it an even 20.

**Comment by JoeBernardi** [comment]
I've limited it to 20. The way the rooms validate before constructing the rooms (i.e., before I'm able to access the lengths of room names) means I'm currently validating them a second time, and there might be a more elegant way to do it, but it works for now. 

There's currently not much of a way to tell what's going on unless you have the console open, though, so maybe an error dialog somewhere, or a hard limit on the amount of characters you can type in the room name area? The way Twitter highlights the characters that are over the character limit is pretty slick, too. @irondavy?
