### ISSUE TITLE
Discuss code formatting conventions

### ISSUE THREAD

**Issue by hoverbird** [ckolderup/picaro#8]
Hey y'all, if this comes off as anal retentive, please close this issue and smack me in the gob.

I've noticed a fair amount of inconsistency in the way the JS and JSON is formatted- a natural case because we're all likely working in different editors.  It's hard to scan the code when the indentation is sometimes 9 spaces, sometimes 8, sometimes a ix of tabs & spaces etc. Tthe fact that some JSON properties are capitalized and some aren't leads to frustration too.  So I'd like to propose a convention for these two things, but I'm less attached to any one style than I am to us all using one style on the project.  Whatever we agree to, I'll volunteer to format all of the code that way in one commit.

My proposal:
  JS indentation should always be 2 spaces (sometimes called 1 "soft tab").  No hard tabs.
  JSON property names should all be camelCased.

What are your thoughts, @JoeBernardi? Do you prefer the super-wide indentation? We could also standardize on 4 spaces, which is pretty common in Python-land.

**Comment by JoeBernardi** [comment]
This is mostly my fault, but I agree that it should be addressed somehow. Your system sounds good to me. (I came to the conclusion during the picaro.js overhaul that all of the JSON properties should be capitalized, but that must have gotten lost in the shuffle.)

So yeah, go for it. 4 space is preferable to 2, to me, but I'm not picky either.

**Comment by hoverbird** [comment]
Cool, thanks Joe.  I'm happy to standardize the JSON properties too- out of curiosity, why uppercase?  Seems to me like more work for the typist (perpetually hitting the shift key) and doesn't map well to JSON data that eventually becomes properties/methods on objects ( syntax like someObject.SomeMethod() is unusual).

**Comment by JoeBernardi** [comment]
It originally made it easier for me to keep track of where I was in the data structure when parsing those objects, but now that that's been cleaned up a whole bunch, I guess I'm casing-agnostic. If you prefer lower/camel case, go for it. Doesn't matter much to me.
